name:                hahascotty
version:             0.1.0.0
github:              "tamaw/hahascotty"
license:             BSD3
author:              "Tama Waddell"
maintainer:          "me@tama.id.au"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tamaw/hahascotty#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- text

library:
  source-dirs: src

executables:
  hahascotty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hahascotty

tests:
  hahascotty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hahascotty
    - QuickCheck
